### PR TITLE
Data Integration and UX Strategies

### PR DESCRIPTION
**Pull request by OjasviSingh**
This document outlines the strategic integration of data and models into the development of a web application for athlete wearable tech sensors, focusing on cycling metrics. It covers data collection, model analysis, and the design of interactive visualizations and user interfaces. The report details how to enhance user interaction through real-time data updates, goal setting, scenario simulations, and community features, inspired by best practices from platforms like TrainerRoad. This is intended to guide the development of a comprehensive, user-friendly, and community-driven platform for cyclists and athletes.

### CODE REVIEW

**Review by SassafrasAU — CHANGES_REQUESTED** [review]
Hi @OjasviSingh 

I'd encourage you to read the readme for this repository, as this documentation site requires all documents to be uploaded as markdown (.md) files.

Examples are here, view the code of these files to see the structure - [Link here](https://redback-operations.github.io/redback-documentation/docs/category/example)

Alternatively I will be releasing a video later today on how to convert a file to markdown and the appropriate steps to uploading to the repo

More than happy to answer any further questions you might have to aide you in successfully uploading this file

**Comment by SassafrasAU** [comment]
I have created a video for you to follow, you can find it here (along with the example page) 

https://redback-operations.github.io/redback-documentation/docs/example/tutorial

**Comment by MorgaineBarter** [comment]
Hey! I just saw this, nice! Please put your link  up on the Mobile Web dev channel in Teams, I am glad you have figured out how to use the UI components, 😊 amusing cat picture.

kind regards
Morgaine Barter

**Review by MorgaineBarter — CHANGES_REQUESTED** [review]
please make the report a MD file before uploading so it is viewable from the webpage

**Comment by SassafrasAU** [comment]
This file has been converted in #14 

For future pull requests, please follow the available tutorials to ensure files are uploaded in markdown

**Pull request closed without merging**
