### PR TITLE
Added Raspeberrypi project

### PR DESCRIPTION
**Pull request by Geetanjali2**
Added Qemu RaspberryPi simulation Pi-hole

### CODE REVIEW

**Comment by AmirZandiehprojects** [comment]
hey please do another PR since there was some issues with the previous PR that caused workflow to trigger issues

**Comment by AmirZandiehprojects** [comment]
Hi @Geetanjali2! Thanks for this detailed documentation on the QEMU Raspberry Pi simulation. I've noticed a few issues causing the build to fail that we can easily fix:

The main issue is with the image paths in your markdown file. The build is failing because it can't find the images due to:
1. The folder name case mismatch ("playbook" vs "Playbook")
2. Using backslashes instead of forward slashes in the paths

For example, change:
`QRPS`
to:
`QRPS`

You'll need to update all image references in your markdown file to use this correct format. Your images are correctly uploaded in the "Playbook" folder (with capital P), so we just need to make sure the markdown references match this exactly.

I also notice some package updates (package.json and yarn.lock) in this PR. While these updates are valid, it might be better to handle dependency updates in a separate PR to keep the changes focused and easier to review.

Let me know if you need any help making these adjustments!

**Comment by Geetanjali2** [comment]
Hi Amir, 

Issues Resolved Can you please review it once again? 

Thank you

**Comment by AmirZandiehprojects** [comment]
@Geetanjali2 Hi , Amazing work thanks !

**Pull request merged**
