### PR TITLE
Added Nagios Preliminary Report

### PR DESCRIPTION
**Pull request by yuhanhb**
## Please check the following - and then delete this message:

- If you are creating a new page, does it contain the following value at the top, with x being the position in the folder?
```
---
sidebar_position: x
---
```

- If you are creating a new sub-folder, does it have a `_category_.json` file with the appropriate descriptive information?
- Are all your images / videos named appropriately and in the correct location ("image1.png" e.g. will not be accepted)
- Are all your code blocks properly closed off?
- Does your file have an appropriate and descriptive file name, and main header?
- Ensure all files are referenced correctly (They are case sensitive - if you save "image.png" you cannot reference "Image.PNG")

Failure to include these will result in your request not being reviewed.

### CODE REVIEW

**Review by yuhanhb — COMMENTED** [review]
Nagios setup

**Review by yuhanhb — COMMENTED** [review]
MQTT Temperature Plugin in Nagios

**Review by SassafrasAU — CHANGES_REQUESTED** [review]
Two small changes then it'll be good:

- Can you delete the duplicate images please "Apache 2 setup for Nagios" and "Port configuration for Nagios"

- As you've got a new folder you'll need a `_category_.json` file to declare the folder. You can copy this from other folders and replace the title / description / position

**Comment by yuhanhb** [comment]
[image: image.png]
Hey Kaleb,

I have made all the changes as requested. I apologize for missing the json
folder setup, big mistake on my end.

Best regards,
Yuhan Perera

**Comment by yuhanhb** [comment]
> Two small changes then it'll be good:
> 
> * Can you delete the duplicate images please "Apache 2 setup for Nagios" and "Port configuration for Nagios"
> * As you've got a new folder you'll need a `_category_.json` file to declare the folder. You can copy this from other folders and replace the title / description / position

Made all the changes as requested.

**Review by yuhanhb — COMMENTED** [review]
Made the folder change and deleted duplicate images.

**Review by SassafrasAU — APPROVED** [review]
Thanks for the changes :)

**Pull request merged**
