### PR TITLE
Initialize Project 2 wiki

### PR DESCRIPTION
**Pull request by Cnalhcal**
This PR will hopefully cure the Elderly IoT wearable team of their writer's block by providing a firm baseline for each subproject identifying the features goal, its dataset and a summary table of the features and any packages that were identified in the main repo as of 05/09/24. 

In the device design folder I have created a basic page out lining the hardware / firmware (heavily based on the readme), As well as a component page providing reasoning and references / datasheets for our components. 

Finally, having identified an issue that the jupyter notebooks are written with no consideration for how others might collaborate. 
I've attempted to alleviate this issue with a best practices file outlining python virtual environments and requirements.txt automated package install lists

### CODE REVIEW

**Review by SassafrasAU — CHANGES_REQUESTED** [review]
Looks good for the most part, handful of small changes need to be made though:

- All folders that contain pages require a `_category_.json` file to give the folder its data. See example [here](https://github.com/Redback-Operations/redback-documentation/blob/main/docs/cybersecurity/Awareness-Training/_category_.json)

- All `.md` files need `sidebar_position: x`, you've got this on some of them, make sure to add it to the rest (with "x" being the relevant position on the sidebar)

- I would suggest changing your headers. Ideally, only the first heading (the page title) is a singular "#", with following headings starting from "##"

With these changes you should be good. And congrats on being pull request #100 ;)

**Comment by Cnalhcal** [comment]
No worries, will update now, thanks! 💯💯💯

**Review by SassafrasAU — APPROVED** [review]
Thanks!

Will approve this, one cosmetic change that I would suggest (but not essential) is replacing you "important" note on line 40 of wearable_device.md with an admonition, just to go with the same syntax used in other documents. [See info here ](https://docusaurus.io/docs/next/markdown-features/admonitions)

**Comment by Cnalhcal** [comment]
Ahh thank you! Yeah I'm not that around MDX and figured bog standard markdown would do the job but I do like the admonition look. Also where would the best spot be for a feature request? I was keen on including some inline LaTeX and tried including the modules but couldn't get them working working and didn't really want to make changes to back end stuff since JS is not my jam.

**Pull request merged**
