### PR TITLE
Wazuh-Virustotal docs

### PR DESCRIPTION
**Pull request by Prabhgun1234**
I have uploaded 4 documents on Wazuh platform.

### CODE REVIEW

**Review by SassafrasAU — APPROVED** [review]
Looks good

**Review by SassafrasAU — APPROVED** [review]
Changed some image paths to work

**Comment by Prabhgun1234** [comment]
Will it be merged today?

**Comment by SassafrasAU** [comment]
I have amended fixes, your images are in the incorrect folder, I have changed their paths to work

**Pull request merged**
