### PR TITLE
Doc for changing from mqtt server to serial connection research Project 1

### PR DESCRIPTION
**Pull request by KrishnPrayag**

### CODE REVIEW

**Comment by KrishnPrayag** [comment]
Added file to facilitate ble connectivity

**Review by SassafrasAU — CHANGES_REQUESTED** [review]
Hi Krishn,

For both files, can you please add 

```
---
sidebar_position: x
---
```

to the very top, change x to 1 and 2 respectively for each file

Overall the BLE file is fine, however regarding the MQTT file, can you please make the following changes:

- The file needs a title, indicated with the `#` symbol
- Several lines such as "Code Example" and "Required Libraries" appear to be sub-headings, and so could have `##` out the front of them, this will help with visibility
- There appears to be lots of whitespace between lines, please remove this
- `<code></code>` blocks need to be replaced with the ` symbol on each side of the code, or ``` for multi-line

Cheers

**Comment by KrishnPrayag** [comment]
Made necessary changes mate!

**Review by MorgaineBarter — APPROVED** [review]
excellent, thanks

**Review by SassafrasAU — APPROVED** [review]

**Pull request merged**
