### PR TITLE
Athlete Wearable Technology Audit Report and Implementation Plan

### PR DESCRIPTION
**Pull request by MoneyMoe1**
Athlete Wearable Technology Audit Report

### CODE REVIEW

**Review by SassafrasAU — CHANGES_REQUESTED** [review]
Both files require a sidebar_position value. Additionally, can you push without deleting the package-lock and yarn lock files please

**Comment by MoneyMoe1** [comment]
It won't let me restore those files

**Comment by MoneyMoe1** [comment]
When I pushed it again it didn't have the files

**Comment by SassafrasAU** [comment]
To avoid issues with the files, I have pushed your two files manually in this commit - https://github.com/Redback-Operations/redback-documentation/commit/84a6d4cdbdf4e5b583955cc7579860510b02dd24

**Comment by MoneyMoe1** [comment]
Thank you for that 🙂

**Pull request closed without merging**
